# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu_bionic64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.1.241"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "E:\\workspace", "/workspace"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    vb.name = "vagrant_nginx_php71"  
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
     vb.memory = "1024"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
      # 设置镜像源
      if [ ! -f "/etc/apt/sources.list.bak" ]; then 
        mv /etc/apt/sources.list /etc/apt/sources.list.bak 
      fi
      if [ -f "/etc/apt/sources.list" ]; then 
        rm /etc/apt/sources.list 
      fi
      ln -s /workspace/vagrant/etc/apt/sources.list.aliyun /etc/apt/sources.list
      
      # 安装 nginx
      apt-get update
      apt-get install -y dkms nginx

      if [ ! -f "/etc/nginx/nginx.conf.bak" ]; then 
        mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
      fi
      if [ -f "/etc/nginx/nginx.conf" ]; then 
        rm /etc/nginx/nginx.conf 
      fi
      ln -s /workspace/vagrant/etc/nginx_vagrant/nginx.conf /etc/nginx/nginx.conf

      # 安装php7.1
      apt-add-repository -y ppa:ondrej/php
      apt-get install -y php7.1 php7.1-cgi php7.1-cli  php7.1-fpm php7.1-phpdbg php7.1-bcmath php7.1-bz2 php7.1-common php7.1-curl php7.1-dba php7.1-enchant php7.1-gd php7.1-gmp php7.1-imap php7.1-interbase php7.1-intl php7.1-json php7.1-ldap php7.1-mbstring php7.1-mcrypt php7.1-mysql php7.1-odbc php7.1-pspell php7.1-readline php7.1-recode php7.1-snmp php7.1-soap php7.1-sqlite3 php7.1-sybase php7.1-tidy php7.1-xml php7.1-xmlrpc php7.1-zip php7.1-opcache php7.1-xsl php7.1-dev

      ln -s /workspace/vagrant/etc/php/7.1/fpm/php.ini /etc/php/7.1/fpm/php.ini
      ln -s /workspace/vagrant/etc/php/7.1/fpm/pool.d/www.conf /etc/php/7.1/fpm/pool.d/www.conf

      systemctl enable nginx
      systemctl enable php7.1-fpm

      systemctl restart nginx
      systemctl restart php7.1-fpm
  SHELL
end
